FROM public.ecr.aws/lambda/nodejs:20

# Copy function code
COPY ./dist/index.js ${LAMBDA_TASK_ROOT}

COPY ./dist/global-bundle.pem ${LAMBDA_TASK_ROOT}
# COPY .env ${LAMBDA_TASK_ROOT}


# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ]